spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        order_by:
          default_null_ordering: last
    open-in-view: false

  main:
    banner-mode: off

  messages:
    encoding: UTF-8

kaggle:
  dataset: https://www.kaggle.com/api/v1/datasets/download/cristaliss/ultimate-book-collection-top-100-books-up-to-2023?datasetVersionNumber=9
  username: andreyvelb
  key: 43dff5c5e911430ab0bac204f38cae07
  file-path: /files/booksFile.csv
